var classes = [
    {
        "name": "App\\Http\\Controllers\\AdminController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "users",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dashboard",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lunasTransaksi",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "menus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateMenu",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteMenu",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\User",
            "App\\Models\\User",
            "App\\Models\\Transaksi",
            "App\\Models\\Transaksi",
            "App\\Models\\User",
            "App\\Models\\Pesanan",
            "App\\Models\\Transaksi",
            "App\\Models\\Pesanan",
            "App\\Models\\Transaksi",
            "App\\Models\\Menu",
            "Illuminate\\Http\\Request",
            "App\\Models\\Menu",
            "App\\Models\\Menu"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 7,
        "length": 131,
        "vocabulary": 57,
        "volume": 764.11,
        "difficulty": 6.35,
        "effort": 4854.34,
        "level": 0.16,
        "bugs": 0.25,
        "time": 270,
        "intelligentContent": 120.28,
        "number_operators": 23,
        "number_operands": 108,
        "number_operators_unique": 6,
        "number_operands_unique": 51,
        "cloc": 7,
        "loc": 59,
        "lloc": 52,
        "mi": 67,
        "mIwoC": 41.57,
        "commentWeight": 25.43,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1089,
        "relativeDataComplexity": 0.26,
        "relativeSystemComplexity": 1089.26,
        "totalStructuralComplexity": 7623,
        "totalDataComplexity": 1.79,
        "totalSystemComplexity": 7624.79,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.11,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\AuthController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "googleCallback",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "me",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userWithProfile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateUsername",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updatePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "uploadPhoto",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 22,
        "ccn": 13,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\User",
            "App\\Models\\Admin",
            "App\\Models\\Merchant",
            "App\\Models\\Pelanggan",
            "Illuminate\\Http\\Request",
            "App\\Models\\User",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Http\\Request",
            "Laravel\\Socialite\\Facades\\Socialite",
            "App\\Models\\User",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\User",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request",
            "App\\Models\\User",
            "Illuminate\\Support\\Str",
            "App\\Models\\User",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 346,
        "vocabulary": 73,
        "volume": 2141.68,
        "difficulty": 12.99,
        "effort": 27809.87,
        "level": 0.08,
        "bugs": 0.71,
        "time": 1545,
        "intelligentContent": 164.93,
        "number_operators": 56,
        "number_operands": 290,
        "number_operators_unique": 6,
        "number_operands_unique": 67,
        "cloc": 156,
        "loc": 299,
        "lloc": 143,
        "mi": 72.9,
        "mIwoC": 27.91,
        "commentWeight": 44.98,
        "kanDefect": 0.85,
        "relativeStructuralComplexity": 1600,
        "relativeDataComplexity": 0.37,
        "relativeSystemComplexity": 1600.37,
        "totalStructuralComplexity": 16000,
        "totalDataComplexity": 3.68,
        "totalSystemComplexity": 16003.68,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.11,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 22,
        "loc": 26,
        "lloc": 4,
        "mi": 220.47,
        "mIwoC": 171,
        "commentWeight": 49.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.32,
        "afferentCoupling": 6,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\MenuController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 11,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Menu",
            "Illuminate\\Http\\Request",
            "App\\Models\\Menu",
            "Illuminate\\Http\\Request",
            "App\\Models\\Menu",
            "Illuminate\\Http\\Request",
            "App\\Models\\Menu"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 168,
        "vocabulary": 45,
        "volume": 922.63,
        "difficulty": 10.23,
        "effort": 9439.23,
        "level": 0.1,
        "bugs": 0.31,
        "time": 524,
        "intelligentContent": 90.18,
        "number_operators": 35,
        "number_operands": 133,
        "number_operators_unique": 6,
        "number_operands_unique": 39,
        "cloc": 1,
        "loc": 60,
        "lloc": 59,
        "mi": 49.06,
        "mIwoC": 39.13,
        "commentWeight": 9.93,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.43,
        "relativeSystemComplexity": 361.43,
        "totalStructuralComplexity": 1444,
        "totalDataComplexity": 1.7,
        "totalSystemComplexity": 1445.7,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.11,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\MerchantController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "dashboard",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pesanan",
            "App\\Models\\Transaksi",
            "App\\Models\\Pesanan",
            "App\\Models\\Transaksi",
            "App\\Models\\Pesanan",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 100,
        "vocabulary": 38,
        "volume": 524.79,
        "difficulty": 6.36,
        "effort": 3339.59,
        "level": 0.16,
        "bugs": 0.17,
        "time": 186,
        "intelligentContent": 82.47,
        "number_operators": 16,
        "number_operands": 84,
        "number_operators_unique": 5,
        "number_operands_unique": 33,
        "cloc": 1,
        "loc": 37,
        "lloc": 36,
        "mi": 58.93,
        "mIwoC": 46.33,
        "commentWeight": 12.6,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 484,
        "relativeDataComplexity": 0.3,
        "relativeSystemComplexity": 484.3,
        "totalStructuralComplexity": 1452,
        "totalDataComplexity": 0.91,
        "totalSystemComplexity": 1452.91,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.11,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\PaymentController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createInvoice",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "webhook",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "markOrderAsPaid",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrderStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 50,
        "ccn": 46,
        "ccnMethodMax": 19,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pesanan",
            "App\\Models\\Order",
            "App\\Models\\Order",
            "App\\Models\\Pesanan",
            "App\\Models\\Order",
            "App\\Models\\Order",
            "Midtrans\\Snap",
            "Illuminate\\Support\\Facades\\Log",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Log",
            "App\\Models\\Order",
            "Illuminate\\Support\\Facades\\Log",
            "Illuminate\\Support\\Facades\\Log",
            "App\\Models\\Pesanan",
            "Illuminate\\Support\\Facades\\Log",
            "Carbon\\Carbon",
            "App\\Models\\Pesanan",
            "Illuminate\\Support\\Facades\\Log",
            "Illuminate\\Http\\Request",
            "App\\Models\\Order",
            "App\\Models\\Pesanan",
            "Carbon\\Carbon"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 395,
        "vocabulary": 96,
        "volume": 2601.06,
        "difficulty": 21.57,
        "effort": 56108.58,
        "level": 0.05,
        "bugs": 0.87,
        "time": 3117,
        "intelligentContent": 120.58,
        "number_operators": 93,
        "number_operands": 302,
        "number_operators_unique": 12,
        "number_operands_unique": 84,
        "cloc": 8,
        "loc": 144,
        "lloc": 136,
        "mi": 41.21,
        "mIwoC": 23.36,
        "commentWeight": 17.85,
        "kanDefect": 2.31,
        "relativeStructuralComplexity": 676,
        "relativeDataComplexity": 0.45,
        "relativeSystemComplexity": 676.45,
        "totalStructuralComplexity": 3380,
        "totalDataComplexity": 2.26,
        "totalSystemComplexity": 3382.26,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.11,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\PesananController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "batalPesanan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 31,
        "ccn": 27,
        "ccnMethodMax": 10,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pesanan",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Pesanan",
            "App\\Models\\Menu",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\DetailPesanan",
            "App\\Models\\Transaksi",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pesanan",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pesanan",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Pesanan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 5,
        "length": 280,
        "vocabulary": 79,
        "volume": 1765.06,
        "difficulty": 19.34,
        "effort": 34142.03,
        "level": 0.05,
        "bugs": 0.59,
        "time": 1897,
        "intelligentContent": 91.25,
        "number_operators": 64,
        "number_operands": 216,
        "number_operators_unique": 12,
        "number_operands_unique": 67,
        "cloc": 181,
        "loc": 291,
        "lloc": 110,
        "mi": 76.09,
        "mIwoC": 29.1,
        "commentWeight": 46.99,
        "kanDefect": 1.68,
        "relativeStructuralComplexity": 441,
        "relativeDataComplexity": 0.7,
        "relativeSystemComplexity": 441.7,
        "totalStructuralComplexity": 2205,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 2208.5,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.11,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    }
]